program: train_model.py
name: ResNet50_pretrained_hyperparameter_tunning
method: random
metric:
  goal: minimize
  name: Val global mean loss per epoch
parameters:
  daug_randomhorizontalflip:
    values:
      - True
      - False
    distribution: categorical
  daug_colorjitter:
    values:
      - True
      - False
    distribution: categorical
  daug_randomaffine:
    values:
      - True
      - False
    distribution: categorical
  daug_randomerasing:
    values:
      - True
      - False
    distribution: categorical
  image_norm:
    values:
      - "imagenet"
      - "affectnet"
    distribution: categorical
  arch:
    values:
      - "resnet50"
  lr:
    values: [0.00001, 0.000001, 0.0000001, 0.00000001]
    distribution: categorical
  batch_size:
    values: [32, 64, 96, 128]
    distribution: categorical
  optimizer:
    values: 
      - "adam"
      - "rmsprop"
      - "sgd"
    distribution: categorical
  momentum:
    max: 1
    min: 0.45
    distribution: uniform
  pretraining:
    values:
     - "imagenet"
  epochs:
    values: 
      - 30
  patience:
    values: 
      - 5
  epoch_samples:
    values: 
      - "original"
  random_seed:
    values:
      - 33
    