preprocessing:
  random_seed: 33
  orig_datasets: ["affectnet"]
  train_split: 0.8 # val size split would be 1 - train_split
  continuous_format: "cartesian"
  face_detection_algorithm: "None" #"Haar Cascade Classifier"

training:
  random_seed: 33 #seed for reproducibility
  data_augmentation: "None"
  image_norm: "ImageNet"
  arch: "ResNet50" # architecture name 
  batch_size: 64 # training and valid batch size
  epoch_samples: 1000 # number of samples considered as one epoch, if None, the whole dataset length is considered
  lr: '1e-5' # learning rate
  momentum: 0.9 # SGD momentum, for SGD only
  optimizer: 'adam' # optimization method: sgd | adam
  epochs: 20  # maximum number of epochs to train
  patience: 5 # how many epochs of no loss improvement should we wait before stop training
  step_log_interval: 10 # how many batches to wait before logging training status
  
  